export const popularDestinationData = [
  {
    id: 1,
    src: "/Bgimg.png",
    continent: "Europe",
    tours: 7,
  },
  {
    id: 2,
    src: "/Bgimg.png",
    continent: "Asia",
    tours: 121,
  },
  {
    id: 3,
    src: "/Bgimg.png",
    continent: "Africa",
    tours: 20,
  },
  {
    id: 4,
    src: "/Bgimg.png",
    continent: "Europe",
    tours: 7,
  },
  {
    id: 5,
    src: "/Bgimg.png",
    continent: "Asia",
    tours: 121,
  },
  {
    id: 6,
    src: "/Bgimg.png",
    continent: "Africa",
    tours: 20,
  },
];

export const productData = [
  {
    id: 1,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 2,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 5,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 151.15,
  },
  {
    id: 3,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 20,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 4,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 1,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 5,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 6,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 176.15,
  },
  {
    id: 7,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 8,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 280.15,
  },
  {
    id: 9,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 10,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 11,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
  {
    id: 12,
    img: "/Bgimg.png",
    name: "Venice, Rome and Milan – 9 Days 8 Nights",
    daysleft: 3,
    location: "Bryce Canyon National Park, USA",
    price: 190.99,
    discountedPrice: 139.15,
  },
];
